import React, { useState } from 'react';
import {
  FileText,
  Image as ImageIcon,
  Copy,
  Check,
  RotateCcw,
  Download,
  FileDown,
  Zap,
  Bookmark,
  Printer,
} from 'lucide-react';
import jsPDF from 'jspdf';
import { SummaryResponse } from '../types';

interface SummaryResultProps {
  result: SummaryResponse;
  onReset: () => void;
}

export const SummaryResult: React.FC<SummaryResultProps> = ({ result, onReset }) => {
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState<string | null>(null);

  const formatDocumentType = (type?: string) => {
    if (!type) return 'GENERAL DOCUMENT';
    switch (type) {
      case 'academic/research':
        return 'ACADEMIC RESEARCH';
      case 'business/report':
        return 'BUSINESS REPORT';
      case 'legal/contract':
        return 'LEGAL CONTRACT';
      default:
        return 'GENERAL DOCUMENT';
    }
  };

  const handleCopySummary = async () => {
    try {
      const textToCopy = `DOCUMENT SUMMARY: ${result.filename}
Type: ${formatDocumentType(result.document_type)}
Length: ${result.length.toUpperCase()} (${result.word_count} words extracted)

EXECUTIVE SUMMARY:
${result.summary}

KEY TAKEAWAYS:
${result.key_points.map((p, i) => `${i + 1}. ${p}`).join('\n')}`;

      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = result.summary;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // 3. EXPORT AS TEXT FILE (.txt)
  const handleDownloadTxt = () => {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeName = result.filename.replace(/\.[^/.]+$/, '');
    const filename = `${safeName}_summary_${result.length}.txt`;

    const content = `================================================================================
DOCUMENT SUMMARY ASSISTANT
================================================================================
Original File : ${result.filename}
Document Type : ${formatDocumentType(result.document_type)}
Brief Length  : ${result.length.toUpperCase()}
Words Parsed  : ${result.word_count}
Generated At  : ${new Date().toLocaleString()}
================================================================================

EXECUTIVE SUMMARY:
--------------------------------------------------------------------------------
${result.summary}

KEY TAKEAWAYS:
--------------------------------------------------------------------------------
${result.key_points.map((point, index) => `[${String(index + 1).padStart(2, '0')}] ${point}`).join('\n\n')}

================================================================================
Distilled via Document Summary Assistant (Groq LLaMA 3.3 70B & Tesseract OCR)
================================================================================
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloaded('txt');
    setTimeout(() => setDownloaded(null), 2500);
  };

  // 3. EXPORT AS MARKDOWN (.md)
  const handleDownloadMarkdown = () => {
    const safeName = result.filename.replace(/\.[^/.]+$/, '');
    const filename = `${safeName}_summary.md`;

    const content = `# Document Summary: ${result.filename}

- **Document Type:** \`${formatDocumentType(result.document_type)}\`
- **Brief Format:** \`${result.length.toUpperCase()}\`
- **Parsed Words:** ${result.word_count} words
- **Date:** ${new Date().toLocaleDateString()}

---

## Executive Summary

${result.summary}

---

## Key Takeaways

${result.key_points.map((point, index) => `${index + 1}. ${point}`).join('\n')}

---
*Generated by Document Summary Assistant*
`;

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloaded('md');
    setTimeout(() => setDownloaded(null), 2500);
  };

  // GENERATE & DOWNLOAD FORMATTED PDF
  const handleDownloadPdf = () => {
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let currentY = margin;

      const checkPageBreak = (neededHeight: number) => {
        if (currentY + neededHeight > pageHeight - margin) {
          doc.addPage();
          currentY = margin;
          return true;
        }
        return false;
      };

      // Header Title
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(26, 26, 26);
      doc.text('DOCUMENT SUMMARY REPORT', margin, currentY);
      currentY += 7;

      // Source Document Filename
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(70, 70, 70);
      const cleanFilename = result.filename || 'Document';
      doc.text(`Source: ${cleanFilename}`, margin, currentY);
      currentY += 6;

      // Metadata Tagline
      doc.setFontSize(9);
      doc.setTextColor(110, 110, 110);
      const metaText = `Type: ${formatDocumentType(result.document_type)}  |  Words Extracted: ${result.word_count.toLocaleString()}  |  Preset: ${result.length.toUpperCase()}  |  Date: ${new Date().toLocaleDateString()}`;
      doc.text(metaText, margin, currentY);
      currentY += 5;

      // Horizontal Divider
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.4);
      doc.line(margin, currentY, margin + contentWidth, currentY);
      currentY += 8;

      // Section 1: Executive Summary
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(13, 92, 70);
      doc.text('EXECUTIVE SUMMARY', margin, currentY);
      currentY += 6;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      const summaryLines = doc.splitTextToSize(result.summary, contentWidth);
      for (let i = 0; i < summaryLines.length; i++) {
        checkPageBreak(5);
        doc.text(summaryLines[i], margin, currentY);
        currentY += 5;
      }
      currentY += 6;

      // Section 2: Key Takeaways
      if (result.key_points && result.key_points.length > 0) {
        checkPageBreak(12);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(13, 92, 70);
        doc.text('KEY TAKEAWAYS', margin, currentY);
        currentY += 7;

        result.key_points.forEach((point, idx) => {
          const numLabel = `${idx + 1}. `;
          const bulletLines = doc.splitTextToSize(point, contentWidth - 8);
          checkPageBreak(bulletLines.length * 5 + 3);

          doc.setFont('helvetica', 'bold');
          doc.setFontSize(10);
          doc.setTextColor(30, 30, 30);
          doc.text(numLabel, margin, currentY);

          doc.setFont('helvetica', 'normal');
          for (let j = 0; j < bulletLines.length; j++) {
            doc.text(bulletLines[j], margin + 6, currentY);
            currentY += 5;
          }
          currentY += 2;
        });
      }

      // Page numbers in footer
      const totalPages = doc.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(140, 140, 140);
        doc.text(
          `Generated by Document Summary Assistant  •  Page ${p} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
      }

      const baseName = result.filename.replace(/\.[^/.]+$/, "") || "summary";
      doc.save(`${baseName}_summary.pdf`);

      setDownloaded('pdf');
      setTimeout(() => setDownloaded(null), 2500);
    } catch (err) {
      console.error('PDF generation error, falling back to window.print():', err);
      window.print();
    }
  };

  const isPdf = result.file_type === 'pdf';

  return (
    <div
      id="summary-result-card"
      className="bg-[var(--surface-card)] rounded border border-[var(--ink-faint)] shadow-sm overflow-hidden animate-fadeIn space-y-6 p-6 sm:p-8 w-full"
    >
      {/* Top Manuscript Docket Bar */}
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-5 pb-5 border-b border-[var(--ink-faint)]">
        <div className="flex items-start gap-3.5 min-w-0 flex-1">
          <div className="w-10 h-10 rounded border border-[var(--accent)] bg-[var(--accent-subtle)] flex items-center justify-center flex-shrink-0 text-[var(--accent)] mt-0.5">
            {isPdf ? <FileText className="w-5 h-5" /> : <ImageIcon className="w-5 h-5" />}
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="label-meta">03 / DOCUMENT SUMMARY</span>
              {result.cached && (
                <span className="inline-flex items-center gap-1 text-[10px] font-mono-code px-1.5 py-0.2 rounded border border-[var(--accent)] text-[var(--accent)] font-semibold">
                  <Zap className="w-3 h-3" /> CACHED
                </span>
              )}
            </div>
            <h2 className="text-base sm:text-lg font-bold font-display uppercase tracking-tight text-[var(--ink)] truncate">
              {result.filename}
            </h2>
            <div className="flex flex-wrap items-center gap-2 text-xs text-[var(--ink-muted)] mt-1 font-mono-code">
              <span>{isPdf ? 'PDF DOCUMENT' : 'SCANNED IMAGE'}</span>
              <span>&bull;</span>
              <span className="text-[var(--accent)] font-semibold">
                {result.word_count.toLocaleString()} WORDS
              </span>
              <span>&bull;</span>
              <span className="uppercase px-1.5 py-0.5 rounded border border-[var(--ink-faint)] text-[var(--ink)]">
                {result.length}
              </span>
              <span>&bull;</span>
              <span className="inline-flex items-center gap-1 text-[var(--ink-muted)]">
                <Bookmark className="w-3 h-3 text-[var(--accent)]" />
                {formatDocumentType(result.document_type)}
              </span>
            </div>
          </div>
        </div>

        {/* Multi-Format Export Options (Stacked vertically one below the other) */}
        <div className="flex flex-col gap-2 flex-shrink-0 w-full sm:w-52">
          <div className="flex items-center justify-between pb-0.5">
            <span className="label-meta text-[10px]">EXPORT OPTIONS</span>
          </div>

          {/* Copy Text Button */}
          <button
            type="button"
            id="copy-summary-button"
            onClick={handleCopySummary}
            className={`w-full flex items-center justify-between px-3 py-2 rounded text-xs font-mono-code uppercase font-semibold border transition-all duration-200 focus:outline-none focus:ring-1 focus:ring-[var(--accent)] min-h-[38px] ${
              copied
                ? 'bg-[var(--accent-subtle)] text-[var(--accent)] border-[var(--accent)]'
                : 'bg-transparent hover:bg-[var(--surface-subtle)] text-[var(--ink)] border-[var(--ink-faint)] hover:border-[var(--ink-muted)]'
            }`}
            title="Copy summary & key points"
          >
            <span className="flex items-center gap-2">
              {copied ? (
                <Check className="w-3.5 h-3.5 text-[var(--accent)]" />
              ) : (
                <Copy className="w-3.5 h-3.5 text-[var(--ink-muted)]" />
              )}
              <span>{copied ? 'COPIED' : 'COPY TEXT'}</span>
            </span>
            <span className="text-[10px] text-[var(--ink-muted)]">[CLIPBOARD]</span>
          </button>

          {/* Export TXT Button */}
          <button
            type="button"
            id="export-txt-button"
            onClick={handleDownloadTxt}
            className={`w-full flex items-center justify-between px-3 py-2 rounded text-xs font-mono-code uppercase font-semibold border transition-all duration-200 focus:outline-none focus:ring-1 focus:ring-[var(--accent)] min-h-[38px] ${
              downloaded === 'txt'
                ? 'bg-[var(--accent-subtle)] text-[var(--accent)] border-[var(--accent)]'
                : 'bg-transparent hover:bg-[var(--surface-subtle)] text-[var(--ink)] border-[var(--ink-faint)] hover:border-[var(--ink-muted)]'
            }`}
            title="Export as plain text file"
          >
            <span className="flex items-center gap-2">
              {downloaded === 'txt' ? (
                <Check className="w-3.5 h-3.5 text-[var(--accent)]" />
              ) : (
                <FileDown className="w-3.5 h-3.5 text-[var(--ink-muted)]" />
              )}
              <span>{downloaded === 'txt' ? 'SAVED .TXT' : 'PLAIN TEXT'}</span>
            </span>
            <span className="text-[10px] text-[var(--ink-muted)]">[.TXT]</span>
          </button>

          {/* Export MD Button */}
          <button
            type="button"
            id="export-md-button"
            onClick={handleDownloadMarkdown}
            className={`w-full flex items-center justify-between px-3 py-2 rounded text-xs font-mono-code uppercase font-semibold border transition-all duration-200 focus:outline-none focus:ring-1 focus:ring-[var(--accent)] min-h-[38px] ${
              downloaded === 'md'
                ? 'bg-[var(--accent-subtle)] text-[var(--accent)] border-[var(--accent)]'
                : 'bg-transparent hover:bg-[var(--surface-subtle)] text-[var(--ink)] border-[var(--ink-faint)] hover:border-[var(--ink-muted)]'
            }`}
            title="Export as Markdown file"
          >
            <span className="flex items-center gap-2">
              {downloaded === 'md' ? (
                <Check className="w-3.5 h-3.5 text-[var(--accent)]" />
              ) : (
                <Download className="w-3.5 h-3.5 text-[var(--ink-muted)]" />
              )}
              <span>{downloaded === 'md' ? 'SAVED .MD' : 'MARKDOWN'}</span>
            </span>
            <span className="text-[10px] text-[var(--ink-muted)]">[.MD]</span>
          </button>

          {/* Download PDF Button */}
          <button
            type="button"
            id="print-summary-button"
            onClick={handleDownloadPdf}
            className={`w-full flex items-center justify-between px-3 py-2 rounded text-xs font-mono-code uppercase font-semibold border transition-all duration-200 focus:outline-none focus:ring-1 focus:ring-[var(--accent)] min-h-[38px] ${
              downloaded === 'pdf'
                ? 'bg-[var(--accent-subtle)] text-[var(--accent)] border-[var(--accent)]'
                : 'bg-transparent hover:bg-[var(--surface-subtle)] text-[var(--ink)] border-[var(--ink-faint)] hover:border-[var(--ink-muted)]'
            }`}
            title="Download structured PDF report"
          >
            <span className="flex items-center gap-2">
              {downloaded === 'pdf' ? (
                <Check className="w-3.5 h-3.5 text-[var(--accent)]" />
              ) : (
                <FileText className="w-3.5 h-3.5 text-[var(--ink-muted)]" />
              )}
              <span>{downloaded === 'pdf' ? 'SAVED .PDF' : 'PDF DOCUMENT'}</span>
            </span>
            <span className="text-[10px] text-[var(--ink-muted)]">[.PDF]</span>
          </button>
        </div>
      </div>

      {/* Executive Summary Section */}
      <div className="space-y-2.5">
        <div className="flex items-center justify-between">
          <span className="label-meta">EXECUTIVE SUMMARY</span>
          <span className="text-[11px] font-mono-code text-[var(--ink-muted)]">
            TYPE: <span className="text-[var(--accent)]">{formatDocumentType(result.document_type)}</span>
          </span>
        </div>
        <div
          id="summary-content-block"
          className="p-5 sm:p-6 bg-[var(--surface-subtle)] rounded border-l-4 border-l-[var(--accent)] border-y border-r border-[var(--ink-faint)]"
        >
          <p className="text-sm sm:text-base leading-relaxed text-[var(--ink)] whitespace-pre-line font-body">
            {result.summary}
          </p>
        </div>
      </div>

      {/* Key Takeaways Section */}
      {result.key_points && result.key_points.length > 0 && (
        <div className="space-y-3">
          <span className="label-meta">KEY TAKEAWAYS</span>
          <div className="grid grid-cols-1 gap-2.5">
            {result.key_points.map((point, index) => (
              <div
                key={index}
                className="flex items-start gap-3.5 p-3.5 sm:p-4 bg-[var(--surface-card)] rounded border border-[var(--ink-faint)] transition-colors hover:border-[var(--accent)] group"
              >
                <div className="mt-0.5 flex-shrink-0 font-mono-code text-xs font-bold text-[var(--accent)]">
                  [{String(index + 1).padStart(2, '0')}]
                </div>
                <p className="text-xs sm:text-sm text-[var(--ink)] leading-relaxed font-body">
                  {point}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer / Reset Action */}
      <div className="pt-4 border-t border-[var(--ink-faint)] flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
        <div className="inline-flex items-center gap-2 font-mono-code text-[11px] text-[var(--accent)]">
          <span className="w-2 h-2 rounded-full bg-[var(--accent)] animate-pulse" />
          <span>INFERENCE_COMPLETE &bull; GROQ LLaMA 3.3 70B</span>
        </div>

        <button
          type="button"
          id="summarize-another-button"
          onClick={onReset}
          className="btn-primary sm:w-auto px-5 py-2.5 text-xs font-display flex items-center justify-center gap-2"
        >
          <RotateCcw className="w-3.5 h-3.5" />
          <span>Summarize Another Document</span>
        </button>
      </div>
    </div>
  );
};
